twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals: 
        serviceDepense: '@App\Service\Business\ServiceDepense'

when@test:
    twig:
        strict_variables: true
