twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals: 
        nameOfApplication : 'Le bon compte'
        serviceDepense: '@App\Service\Business\ServiceDepense'
        serviceDepenseUser: '@App\Service\Business\ServiceDepenseUser'
        serviceFamily: '@App\Service\Business\ServiceFamily'
        serviceDepenseFamily: '@App\Service\Business\ServiceDepenseFamily'

when@test:
    twig:
        strict_variables: true
