services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - .:/app
      - /app/vendor
    environment:
      DATABASE_URL: mysql://root:password@database:3306/depense
      APP_ENV: dev
      APP_SECRET: 1234567890abcdef
    depends_on:
      - database

  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: depense
    ports:
      - "3307:3306"
    expose:
      - "3306"
